console.log("Cabeçalho com imagem")
console.log("Logo abaixo Titulo sobre o que a página fala")
console.log("Tabela com imagens e texto  (em forma de botão) sobre o Top 10")
console.log("Video de trailer do filme")
console.log("Rodapé com logo da Marvel")